server.port=8081
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:reports-realm}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:reports-frontend}
security.access-token-ttl=${ACCESS_TOKEN_TTL:120}
security.session-ttl=${SESSION_TTL:7200}
security.encryption-key=${ENCRYPTION_KEY:mySecretKey12345678}